AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  picturePOST:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::889017460304:role/service-role/hello_world-role-uju2641b'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/students/{student_id}/picture'
            Method: POST
